import pygame


class Map:
    def __init__(self, num_map):
        self.num_map = num_map
        self.width = None
        self.height = None
        self.tile_size = 50
        self.imbg1 = pygame.image.load('images/обычная трава.png').convert_alpha()
        self.imbg2 = pygame.image.load('images/препятствие.png').convert_alpha()
        # Добавьте здесь код для загрузки карты, тайлов и других параметров.

    def View_world(self, view_world):
        if view_world == 1:
            world = ["NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN",
                     "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN",
                     "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN",
                     "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN",
                     "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN",
                     "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN",
                     "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN",
                     "NNNNNNNNNNNNNNTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTNNNNNNNNNNNNN",
                     "NNNNNNNNNNNNNNTBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBTNNNNNNNNNNNNN",
                     "NNNNNNNNNNNNNNTBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBTNNNNNNNNNNNNN",
                     "NNNNNNNNNNNNNNTBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBTNNNNNNNNNNNNN",
                     "NNNNNNNNNNNNNNTBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBTNNNNNNNNNNNNN",
                     "NNNNNNNNNNNNNNTBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBTNNNNNNNNNNNNN",
                     "NNNNNNNNNNNNNNTBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBTNNNNNNNNNNNNN",
                     "NNNNNNNNNNNNNNTBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBTNNNNNNNNNNNNN",
                     "NNNNNNNNNNNNNNTBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBTNNNNNNNNNNNNN",
                     "NNNNNNNNNNNNNNTBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBTNNNNNNNNNNNNN",
                     "NNNNNNNNNNNNNNTBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBTNNNNNNNNNNNNN",
                     "NNNNNNNNNNNNNNTBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBTNNNNNNNNNNNNN",
                     "NNNNNNNNNNNNNNTBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBTNNNNNNNNNNNNN",
                     "NNNNNNNNNNNNNNTBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBTNNNNNNNNNNNNN",
                     "NNNNNNNNNNNNNNTBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBTNNNNNNNNNNNNN",
                     "NNNNNNNNNNNNNNTBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBTNNNNNNNNNNNNN",
                     "NNNNNNNNNNNNNNTBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBTNNNNNNNNNNNNN",
                     "NNNNNNNNNNNNNNTBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBTNNNNNNNNNNNNN",
                     "NNNNNNNNNNNNNNTBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBTNNNNNNNNNNNNN",
                     "NNNNNNNNNNNNNNTBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBTNNNNNNNNNNNNN",
                     "NNNNNNNNNNNNNNTBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBTNNNNNNNNNNNNN",
                     "NNNNNNNNNNNNNNTBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBTNNNNNNNNNNNNN",
                     "NNNNNNNNNNNNNNTBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBTNNNNNNNNNNNNN",
                     "NNNNNNNNNNNNNNTBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBTNNNNNNNNNNNNN",
                     "NNNNNNNNNNNNNNTBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBTNNNNNNNNNNNNN",
                     "NNNNNNNNNNNNNNTBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBTNNNNNNNNNNNNN",
                     "NNNNNNNNNNNNNNTBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBTNNNNNNNNNNNNN",
                     "NNNNNNNNNNNNNNTBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBTNNNNNNNNNNNNN",
                     "NNNNNNNNNNNNNNTBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBTNNNNNNNNNNNNN",
                     "NNNNNNNNNNNNNNTBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBTNNNNNNNNNNNNN",
                     "NNNNNNNNNNNNNNTBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBTNNNNNNNNNNNNN",
                     "NNNNNNNNNNNNNNTBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBTNNNNNNNNNNNNN",
                     "NNNNNNNNNNNNNNTBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBTNNNNNNNNNNNNN",
                     "NNNNNNNNNNNNNNTBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBTNNNNNNNNNNNNN",
                     "NNNNNNNNNNNNNNTBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBTNNNNNNNNNNNNN",
                     "NNNNNNNNNNNNNNTBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBTNNNNNNNNNNNNN",
                     "NNNNNNNNNNNNNNTBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBTNNNNNNNNNNNNN",
                     "NNNNNNNNNNNNNNTBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBTNNNNNNNNNNNNN",
                     "NNNNNNNNNNNNNNTBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBTNNNNNNNNNNNNN",
                     "NNNNNNNNNNNNNNTBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBTNNNNNNNNNNNNN",
                     "NNNNNNNNNNNNNNTBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBTNNNNNNNNNNNNN",
                     "NNNNNNNNNNNNNNTBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBTNNNNNNNNNNNNN",
                     "NNNNNNNNNNNNNNTBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBTNNNNNNNNNNNNN",
                     "NNNNNNNNNNNNNNTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTNNNNNNNNNNNNN",
                     "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN",
                     "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN",
                     "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN",
                     "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN",
                     "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN",
                     ]
            self.width = len(world[0]) * self.tile_size - 15
            self.height = len(world) * self.tile_size
            data = (world, self.width, self.height,)
        return data

    def DRAWMAP(self, win, camera):
        world = self.View_world(self.num_map)[0]
        tile_Size = 50
        win.fill('black')
        for row in range(len(world)):
            for col in range(len(world[row])):
                x = col * tile_Size
                y = row * tile_Size

                if world[row][col] == 'B':
                    tile_rect = pygame.Rect(x, y, tile_Size, tile_Size)
                    shifted_tile_rect = camera.apply(tile_rect)  # Применить сдвиг к тайлу
                    win.blit(self.imbg1, shifted_tile_rect)
                elif world[row][col] == 'T':
                    tile_rect = pygame.Rect(x, y, tile_Size, tile_Size)
                    shifted_tile_rect = camera.apply(tile_rect)  # Применить сдвиг к тайлу
                    win.blit(self.imbg2, shifted_tile_rect)
                else:
                    pygame.draw.rect(win, 'blue', camera.apply(pygame.Rect(x, y, tile_Size, tile_Size)))
        return win

    def H_W(self):
        data = (self.View_world(self.num_map)[1], self.View_world(self.num_map)[2])
        return data